name: Markdown Link Checker

on: 
  push:
    branches:
    - main
  schedule:
  # Run everyday at 9:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
  - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  markdown-link-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: markdown-link-check
      id: markdownlinkcheck
      continue-on-error: true
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
    - name: Sleep for 3hrs
      if: ${{ steps.markdownlinkcheck.outcome == 'failure' && steps.markdownlinkcheck.conclusion == 'success' }}
      uses: juliangruber/sleep-action@v1
      with:
        time: 10800s #Sleep for 3hrs. In case link host is offline for maintenance.
    - name: markdown-link-check-retry
      if: ${{ steps.markdownlinkcheck.outcome == 'failure' && steps.markdownlinkcheck.conclusion == 'success' }}
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
